#!/bin/bash

volume=$(pactl list sinks | grep 'Volume:' | awk 'NR==7 {print $5}' | sed 's/%//')
mute=$(pactl list sinks | grep 'Mute:' | awk 'NR==4 {print $2}')

if [ "$mute" == "yes" ]; then
  icon="󰖁"
else
  if [ "$volume" -eq 0 ]; then
    icon=""
  elif [ "$volume" -lt 50 ]; then
    icon=""
  else
    icon=""
  fi
fi

echo "$icon $volume%"
